version: "3.8"

# Quick Start:
# 1. Build the Docker image: docker-compose build
# 2. Push the image to your container registry
# 3. Deploy to Dokploy, ensuring all required environment variables are set.
#
# Required environment variables (set in Dokploy):
# - DB_HOST, DB_NAME, DB_USERNAME, DB_PASSWORD: PostgreSQL credentials
# - DB_REDIS_URI: Redis connection URI
# - JWT_SECRET_KEY: At least 32 characters
# - ADMIN_EMAIL, ADMIN_USERNAME, ADMIN_PASSWORD: Admin account
# - EASYKASH_PRIVATE_KEY, EASYKASH_SECRET_KEY: Payment gateway
# - CORS_ORIGIN: Your frontend URL

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/app/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
