"""Add activity_details to Invoice table

Revision ID: 008673aef4fc
Revises: eca72b45033c
Create Date: 2025-10-24 16:43:08.274741

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "008673aef4fc"
down_revision: Union[str, Sequence[str], None] = "eca72b45033c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add activity_details column to invoices table if it doesn't exist
    # Using raw SQL to handle the case where column might already exist
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.columns 
                WHERE table_name = 'invoices' AND column_name = 'activity_details'
            ) THEN
                ALTER TABLE invoices ADD COLUMN activity_details JSONB;
            END IF;
        END $$;
    """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove activity_details column from invoices table
    op.drop_column("invoices", "activity_details")
    # ### end Alembic commands ###
