"""Edit trip column

Revision ID: 028bd0e0e689
Revises: fd973c4586b7
Create Date: 2025-08-30 12:31:49.292611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '028bd0e0e689'
down_revision: Union[str, Sequence[str], None] = 'fd973c4586b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('duration_unit', sa.String(length=20), nullable=True))
    op.alter_column('trips', 'duration',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text('8'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trips', 'duration',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text('8'))
    op.drop_column('trips', 'duration_unit')
    # ### end Alembic commands ###
