"""Edit invoice column

Revision ID: 0530a1253e11
Revises: 5ad36abcca5b
Create Date: 2025-08-29 15:25:07.252362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0530a1253e11'
down_revision: Union[str, Sequence[str], None] = '5ad36abcca5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('pay_url', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'pay_url')
    # ### end Alembic commands ###
