"""add fees and transfer_fees tables

Revision ID: 1c8ba86730bc
Revises: 
Create Date: 2026-06-28 20:29:03.628742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c8ba86730bc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer_zones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('trip_fees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('fee_type', sa.Enum('fixed', 'percentage', name='fee_type_enum'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('applies_to', sa.Enum('per_booking', 'per_person', 'per_adult', 'per_child', name='fee_applies_to_enum'), nullable=False),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('is_included_in_price', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trip_transfer_fees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('fee_type', sa.Enum('fixed', 'percentage', name='fee_type_enum'), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('applies_to', sa.Enum('per_booking', 'per_person', 'per_adult', 'per_child', name='fee_applies_to_enum'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['transfer_zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('invoices', sa.Column('price_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'price_breakdown')
    op.drop_table('trip_transfer_fees')
    op.drop_table('trip_fees')
    op.drop_table('transfer_zones')
    # ### end Alembic commands ###
