"""Edit the course table

Revision ID: 207515d9d8e8
Revises: b609c2ecd9f9
Create Date: 2025-08-03 00:55:23.757363

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "207515d9d8e8"
down_revision: Union[str, Sequence[str], None] = "b609c2ecd9f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "courses", sa.Column("course_type", sa.String(length=100), nullable=False)
    )
    op.add_column(
        "courses",
        sa.Column(
            "has_certificate", sa.Boolean(), server_default=sa.text("1"), nullable=False
        ),
    )
    op.add_column(
        "courses", sa.Column("certificate_type", sa.String(length=100), nullable=False)
    )
    op.add_column(
        "courses",
        sa.Column(
            "has_online_content",
            sa.Boolean(),
            server_default=sa.text("1"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("courses", "has_online_content")
    op.drop_column("courses", "certificate_type")
    op.drop_column("courses", "has_certificate")
    op.drop_column("courses", "course_type")
    op.create_table(
        "images",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column("name", mysql.VARCHAR(length=100), nullable=False),
        sa.Column("url", mysql.VARCHAR(length=100), nullable=False),
        sa.Column(
            "gallery_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("created_at", mysql.DATETIME(), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(["gallery_id"], ["galleries.id"], name="images_ibfk_1"),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_general_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "galleries",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column("name", mysql.VARCHAR(length=100), nullable=False),
        sa.Column("description", mysql.VARCHAR(length=500), nullable=True),
        sa.Column("created_at", mysql.DATETIME(), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_general_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
