"""Edit invoice table

Revision ID: 4cdeb42fca1d
Revises: cdd57f591b4c
Create Date: 2025-08-29 02:00:27.874461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4cdeb42fca1d'
down_revision: Union[str, Sequence[str], None] = 'cdd57f591b4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('buyer_name', sa.String(length=100), nullable=False))
    op.add_column('invoices', sa.Column('buyer_email', sa.String(length=100), nullable=False))
    op.add_column('invoices', sa.Column('buyer_phone', sa.String(length=100), nullable=False))
    op.add_column('invoices', sa.Column('invoice_description', sa.Text(), nullable=False))
    op.add_column('invoices', sa.Column('activity', sa.String(length=100), nullable=False))
    op.add_column('invoices', sa.Column('currency', sa.String(length=50), nullable=False))
    op.add_column('invoices', sa.Column('payment_method', sa.String(length=50), nullable=False))
    op.add_column('invoices', sa.Column('customer_reference', sa.String(length=50), nullable=True))
    op.add_column('invoices', sa.Column('easykash_reference', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'invoices', ['customer_reference'])
    op.create_unique_constraint(None, 'invoices', ['easykash_reference'])
    op.drop_column('invoices', 'pay_url')
    op.drop_column('invoices', 'items')
    op.drop_column('invoices', 'updated_at')
    op.drop_column('invoices', 'invoice_for')
    op.drop_column('invoices', 'pay_method')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('pay_method', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('invoices', sa.Column('invoice_for', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('invoices', sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False))
    op.add_column('invoices', sa.Column('items', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=False))
    op.add_column('invoices', sa.Column('pay_url', mysql.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'invoices', type_='unique')
    op.drop_constraint(None, 'invoices', type_='unique')
    op.drop_column('invoices', 'easykash_reference')
    op.drop_column('invoices', 'customer_reference')
    op.drop_column('invoices', 'payment_method')
    op.drop_column('invoices', 'currency')
    op.drop_column('invoices', 'activity')
    op.drop_column('invoices', 'invoice_description')
    op.drop_column('invoices', 'buyer_phone')
    op.drop_column('invoices', 'buyer_email')
    op.drop_column('invoices', 'buyer_name')
    # ### end Alembic commands ###
