"""Edit trip table

Revision ID: 537ff0a254db
Revises: cfadaa598bd6
Create Date: 2025-08-29 02:33:55.815716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '537ff0a254db'
down_revision: Union[str, Sequence[str], None] = 'cfadaa598bd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('egp_adult_price', sa.Float(), nullable=False))
    op.add_column('trips', sa.Column('egp_child_price', sa.Float(), nullable=False))
    op.add_column('trips', sa.Column('usd_adult_price', sa.Float(), nullable=False))
    op.add_column('trips', sa.Column('usd_child_price', sa.Float(), nullable=False))
    op.add_column('trips', sa.Column('euro_adult_price', sa.Float(), nullable=False))
    op.add_column('trips', sa.Column('euro_child_price', sa.Float(), nullable=False))
    op.drop_column('trips', 'adult_price')
    op.drop_column('trips', 'child_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('child_price', mysql.FLOAT(), nullable=False))
    op.add_column('trips', sa.Column('adult_price', mysql.FLOAT(), nullable=False))
    op.drop_column('trips', 'euro_child_price')
    op.drop_column('trips', 'euro_adult_price')
    op.drop_column('trips', 'usd_child_price')
    op.drop_column('trips', 'usd_adult_price')
    op.drop_column('trips', 'egp_child_price')
    op.drop_column('trips', 'egp_adult_price')
    # ### end Alembic commands ###
