"""Edit Course Table and add provider

Revision ID: 6e5f44d41619
Revises: 5b007089c404
Create Date: 2025-08-05 17:00:32.085184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6e5f44d41619'
down_revision: Union[str, Sequence[str], None] = '5b007089c404'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('provider', sa.String(length=100), server_default='Padi', nullable=False))
    op.alter_column('courses', 'description',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=10000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'description',
               existing_type=sa.String(length=10000),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_column('courses', 'provider')
    # ### end Alembic commands ###
