"""add_coupon_feature

Revision ID: 7010085e5701
Revises: cc5e0000f35e
Create Date: 2025-12-20 13:58:45.882289

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7010085e5701"
down_revision: Union[str, Sequence[str], None] = "cc5e0000f35e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c["name"] for c in inspector.get_columns("coupons")]

    if "discount_percentage" not in columns:
        op.add_column(
            "coupons", sa.Column("discount_percentage", sa.Float(), nullable=False)
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("coupons", "discount_percentage")
    op.drop_table("best_selling")
    op.drop_index(op.f("ix_gallery_name"), table_name="gallery")
    op.drop_index(op.f("ix_gallery_id"), table_name="gallery")
    op.drop_table("gallery")
    op.drop_table("dive_centers")
    # ### end Alembic commands ###
