"""Edit course column

Revision ID: 82e198222210
Revises: 028bd0e0e689
Create Date: 2025-08-31 16:51:11.740560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82e198222210'
down_revision: Union[str, Sequence[str], None] = '028bd0e0e689'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('course_duration_unit', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'course_duration_unit')
    # ### end Alembic commands ###
