"""Edit some tables course and package and trips

Revision ID: 8862bef43da9
Revises: 60b565e8428b
Create Date: 2025-07-20 21:36:28.744051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8862bef43da9'
down_revision: Union[str, Sequence[str], None] = '60b565e8428b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('packages', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('trips', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('trips', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'updated_at')
    op.drop_column('trips', 'created_at')
    op.drop_column('packages', 'updated_at')
    op.drop_column('packages', 'created_at')
    # ### end Alembic commands ###
