"""edit invoice and add convert_rate

Revision ID: 8d1e5cf4697f
Revises: d3c2bd806ebc
Create Date: 2026-02-04 19:46:09.952256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d1e5cf4697f'
down_revision: Union[str, Sequence[str], None] = 'd3c2bd806ebc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('convert_rate', sa.Float(), server_default='1.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'convert_rate')
    # ### end Alembic commands ###
