"""Edit invoice column

Revision ID: a22605bffcdb
Revises: 6a72b6093cef
Create Date: 2025-08-29 22:30:43.332918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a22605bffcdb'
down_revision: Union[str, Sequence[str], None] = '6a72b6093cef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('picked_up', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'picked_up')
    # ### end Alembic commands ###
