"""migrate

Revision ID: cdd57f591b4c
Revises: e24f1819d5f7
Create Date: 2025-08-09 20:36:16.757753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdd57f591b4c'
down_revision: Union[str, Sequence[str], None] = 'e24f1819d5f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dive_centers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=10000), nullable=True),
    sa.Column('images', sa.JSON(), nullable=False),
    sa.Column('is_image_list', sa.Boolean(), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('hotel_name', sa.String(length=255), nullable=True),
    sa.Column('coordinates', sa.JSON(), nullable=True),
    sa.Column('working_hours', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('best_selling',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_type', sa.Enum('COURSE', 'TRIP', name='itemtype'), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('ranking_position', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('testimonials_ibfk_2'), 'testimonials', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('testimonials_ibfk_2'), 'testimonials', 'users', ['user_id'], ['id'])
    op.drop_table('best_selling')
    op.drop_table('dive_centers')
    # ### end Alembic commands ###
