"""Edit trip price column

Revision ID: cf2ce360aad9
Revises: a22605bffcdb
Create Date: 2025-08-29 23:31:13.421380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cf2ce360aad9'
down_revision: Union[str, Sequence[str], None] = 'a22605bffcdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('child_allowed', sa.Boolean(), server_default=sa.text('0'), nullable=True))
    op.add_column('trips', sa.Column('discount_requires_min_people', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.add_column('trips', sa.Column('discount_always_available', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.add_column('trips', sa.Column('discount_min_people', sa.Integer(), nullable=True))
    op.alter_column('trips', 'has_discount',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trips', 'has_discount',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('trips', 'discount_min_people')
    op.drop_column('trips', 'discount_always_available')
    op.drop_column('trips', 'discount_requires_min_people')
    op.drop_column('trips', 'child_allowed')
    # ### end Alembic commands ###
