"""edit admin table

Revision ID: d04e6a80d1c8
Revises: fa6e4f4a9ecf
Create Date: 2025-07-31 19:31:53.320296

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "d04e6a80d1c8"
down_revision: Union[str, Sequence[str], None] = "fa6e4f4a9ecf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "admins",
        sa.Column(
            "is_active",
            sa.String(length=40),
            server_default=sa.text("'true'"),
            nullable=False,
        ),
    )
    op.add_column(
        "admins",
        sa.Column(
            "last_login",
            sa.String(length=50),
            server_default=sa.text("'null'"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("admins", "last_login")
    op.drop_column("admins", "is_active")
    op.create_table(
        "images",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column("name", mysql.VARCHAR(length=100), nullable=False),
        sa.Column("url", mysql.VARCHAR(length=100), nullable=False),
        sa.Column(
            "gallery_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("created_at", mysql.DATETIME(), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(["gallery_id"], ["galleries.id"], name="images_ibfk_1"),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_general_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "galleries",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column("name", mysql.VARCHAR(length=100), nullable=False),
        sa.Column("description", mysql.VARCHAR(length=500), nullable=True),
        sa.Column("created_at", mysql.DATETIME(), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_general_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
