"""update_coupon_future

Revision ID: d1d0fdc84c55
Revises: 7010085e5701
Create Date: 2025-12-20 15:20:55.815269

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d1d0fdc84c55"
down_revision: Union[str, Sequence[str], None] = "7010085e5701"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # Check coupon_user_usage columns
    usage_columns = [c["name"] for c in inspector.get_columns("coupon_user_usage")]
    if "usage_count" not in usage_columns:
        op.add_column(
            "coupon_user_usage",
            sa.Column(
                "usage_count", sa.Integer(), nullable=False, server_default=sa.text("1")
            ),
        )

    # Check coupons columns
    coupon_columns = [c["name"] for c in inspector.get_columns("coupons")]
    if "user_limit" not in coupon_columns:
        op.add_column(
            "coupons",
            sa.Column(
                "user_limit", sa.Integer(), server_default=sa.text("1"), nullable=False
            ),
        )

    # Check invoices columns
    invoice_columns = [c["name"] for c in inspector.get_columns("invoices")]
    if "coupon_code" not in invoice_columns:
        op.add_column(
            "invoices", sa.Column("coupon_code", sa.String(length=50), nullable=True)
        )
    if "discount_amount" not in invoice_columns:
        op.add_column(
            "invoices", sa.Column("discount_amount", sa.Float(), nullable=True)
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invoices", "discount_amount")
    op.drop_column("invoices", "coupon_code")
    op.drop_column("coupons", "user_limit")
    op.drop_column("coupon_user_usage", "usage_count")
    # ### end Alembic commands ###
