"""add video to dive-center

Revision ID: d3c2bd806ebc
Revises: 7ed49fe7590f
Create Date: 2026-01-26 15:50:40.777476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3c2bd806ebc'
down_revision: Union[str, Sequence[str], None] = '7ed49fe7590f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_availability_lookup'), table_name='activity_availability')
    op.add_column('dive_centers', sa.Column('video', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dive_centers', 'video')
    op.create_index(op.f('ix_activity_availability_lookup'), 'activity_availability', ['activity_type', 'activity_id', 'date'], unique=False)
    # ### end Alembic commands ###
