"""add new trip offer and bundle future

Revision ID: d6b733139524
Revises: e82bb5dd9c13
Create Date: 2026-07-03 01:58:40.385408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6b733139524'
down_revision: Union[str, Sequence[str], None] = 'e82bb5dd9c13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('trip_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'invoices', 'trips', ['trip_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'trip_id')
    # ### end Alembic commands ###
