"""edit notification table

Revision ID: e24f1819d5f7
Revises: 6e5f44d41619
Create Date: 2025-08-09 20:34:47.156087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e24f1819d5f7'
down_revision: Union[str, Sequence[str], None] = '6e5f44d41619'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_constraint(op.f('invoices_ibfk_1'), 'invoices', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('notifications', sa.Column('type', sa.String(length=50), nullable=False))
    op.drop_constraint(op.f('testimonials_ibfk_1'), 'testimonials', type_='foreignkey')
    op.create_foreign_key(None, 'testimonials', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_course_subscriptions', 'subscribed_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_constraint(op.f('user_course_subscriptions_ibfk_1'), 'user_course_subscriptions', type_='foreignkey')
    op.drop_constraint(op.f('user_course_subscriptions_ibfk_2'), 'user_course_subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'user_course_subscriptions', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_course_subscriptions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_course_subscriptions', type_='foreignkey')
    op.drop_constraint(None, 'user_course_subscriptions', type_='foreignkey')
    op.create_foreign_key(op.f('user_course_subscriptions_ibfk_2'), 'user_course_subscriptions', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(op.f('user_course_subscriptions_ibfk_1'), 'user_course_subscriptions', 'users', ['user_id'], ['id'])
    op.alter_column('user_course_subscriptions', 'subscribed_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_constraint(None, 'testimonials', type_='foreignkey')
    op.create_foreign_key(op.f('testimonials_ibfk_1'), 'testimonials', 'users', ['user_id'], ['id'])
    op.drop_column('notifications', 'type')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.create_foreign_key(op.f('invoices_ibfk_1'), 'invoices', 'users', ['user_id'], ['id'])
    op.create_table('dive_centers',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=10000), nullable=True),
    sa.Column('images', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=False),
    sa.Column('is_image_list', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('location', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('hotel_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('coordinates', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.Column('working_hours', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('best_selling',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('item_type', mysql.ENUM('COURSE', 'TRIP'), nullable=False),
    sa.Column('item_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('ranking_position', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('course_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('trip_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('best_selling_ibfk_1')),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('best_selling_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
