"""add new trip offer and bundle future

Revision ID: e82bb5dd9c13
Revises: 1c8ba86730bc
Create Date: 2026-07-03 00:22:20.443282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e82bb5dd9c13'
down_revision: Union[str, Sequence[str], None] = '1c8ba86730bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_bundle_offers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('offer_trip_id', sa.Integer(), nullable=False),
    sa.Column('discount_type', sa.Enum('percentage', 'fixed', 'free', name='discount_type'), nullable=False),
    sa.Column('discount_value', sa.Float(), nullable=False),
    sa.Column('min_required_trips', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['offer_trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trip_packages',
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trip_id', 'package_id')
    )
    op.create_table('trip_relations',
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('related_trip_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['related_trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trip_id', 'related_trip_id')
    )
    op.create_table('trip_bundle_requirements',
    sa.Column('bundle_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bundle_id'], ['trip_bundle_offers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bundle_id', 'trip_id')
    )
    op.drop_constraint(op.f('trips_package_id_fkey'), 'trips', type_='foreignkey')
    op.drop_column('trips', 'package_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('package_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('trips_package_id_fkey'), 'trips', 'packages', ['package_id'], ['id'])
    op.drop_table('trip_bundle_requirements')
    op.drop_table('trip_relations')
    op.drop_table('trip_packages')
    op.drop_table('trip_bundle_offers')
    # ### end Alembic commands ###
