"""edit_blog

Revision ID: f249bd340f49
Revises: bf51e1143e86
Create Date: 2025-12-24 20:40:00.825383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f249bd340f49'
down_revision: Union[str, Sequence[str], None] = 'bf51e1143e86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('content', mysql.JSON(), nullable=False))
    op.drop_column('blogs', 'blog_text')
    op.drop_column('blogs', 'images')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('images', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('blogs', sa.Column('blog_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('blogs', 'content')
    # ### end Alembic commands ###
