"""edit test

Revision ID: fa6e4f4a9ecf
Revises: eb94e6a0a4aa
Create Date: 2025-07-31 01:59:49.926701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fa6e4f4a9ecf'
down_revision: Union[str, Sequence[str], None] = 'eb94e6a0a4aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('galleries')
    op.drop_table('images')
    op.add_column('testimonials', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'testimonials', 'users', ['user_id'], ['id'])
    op.drop_column('testimonials', 'testimonial_owner')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testimonials', sa.Column('testimonial_owner', mysql.VARCHAR(length=100), nullable=False))
    op.drop_constraint(None, 'testimonials', type_='foreignkey')
    op.drop_column('testimonials', 'user_id')
    op.create_table('images',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('url', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('gallery_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['gallery_id'], ['galleries.id'], name='images_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('galleries',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
