"""Edit course column

Revision ID: fd973c4586b7
Revises: af5a21590e57
Create Date: 2025-08-30 12:03:48.598226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd973c4586b7'
down_revision: Union[str, Sequence[str], None] = 'af5a21590e57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('price_available', sa.Boolean(), server_default=sa.text('1'), nullable=False))
    op.add_column('courses', sa.Column('has_discount', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.add_column('courses', sa.Column('discount_requires_min_people', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.add_column('courses', sa.Column('discount_always_available', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.add_column('courses', sa.Column('discount_min_people', sa.Integer(), nullable=True))
    op.add_column('courses', sa.Column('discount_percentage', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'discount_percentage')
    op.drop_column('courses', 'discount_min_people')
    op.drop_column('courses', 'discount_always_available')
    op.drop_column('courses', 'discount_requires_min_people')
    op.drop_column('courses', 'has_discount')
    op.drop_column('courses', 'price_available')
    # ### end Alembic commands ###
